### ISSUE TITLE
wide character in syswrite error sending via SMTP

### ISSUE THREAD

**Issue by trwww** [dhoss/catalyst-view-email#12]
I've got encoding issues as well, but they look a little different than the other open issue so opening a new one. When I try to send an email that has non ascii characters in the body or subject I get:

[error] Caught exception in TestApp::View::EmailSMTP->process "Wide character in syswrite at /home/trwww/livechatbot/perl/lib/site_perl/5.18.2/Net/Cmd.pm line 212."

The issue goes away if I downgrade libnet to 3.06 and comment out the utf8::downgrade call in Email::Sender::Transport::SMTP.

I couldn't duplicate this using Email::Sender / Email::Sender::Transport::SMTP directly.

I put together a test case by modifying the C::V::E test suite at:

https://github.com/trwww/catalyst-view-email/commit/111fce0e5d8499c609317ae866bef2fc13e41610.patch

This is on perl 5.18.2 with completely up-to-date modules via the cpan shell's upgrade command.

**Comment by rjbs** [comment]
From what I can tell, the `body` argument ends up getting passed to `Email::MIME->create(body => $HERE)`.  You must not put *text* there, but *bytes*.

The argument for passing a *text* body to Email::MIME::create is *body_str*.  If you provide text to *body*, and if there are wide characters, you may very well end up with this problem.

I don't know enough about Catalyst::View::Email to suggest whether the problem is with your code or with Catalyst::View::Email, but it's probably clear to anyone who knows C::V::E.

**Comment by Altreus** [comment]
C:V:E understands `body` but not `body_str`

https://github.com/dhoss/catalyst-view-email/blob/master/lib/Catalyst/View/Email.pm#L282

This means you have to encode your body before you send it, or construct your own `parts` arrayref with `body_str` in it.

It looks like it would be simple to patch this to also understand `body_str`, it just hasn't been done yet.

**Comment by dhoss** [comment]
Hey, I'm not really involved with this anymore but if it's all good I'll merge it in
